### ISSUE TITLE
请问可以出一个详细一点的使用教程吗？

### ISSUE THREAD

**Issue by LemonDrug** [l-qiang/LitterBaby#2]
因为并未接触过Java语言，在安装配置的时候出现了大量问题，本人愚钝，研究了两天也没有得到解决。
目前所有JDK8、Android SDK 24.4.1、Appium 1.15.1、夜神模拟器，全部已经安装好，并且通过ADB可以查找到夜神设备。
但是并不知道下一步应该怎么做，无法打开http://localhost:8080/start与http://localhost:8080/h2。
Download整个项目后，应该如何使用呢？
希望有大神或者作者大大帮忙解决一下，多谢了。

**Comment by wyap-echo** [comment]
老哥 搞好了吗 我也没搞明白

**Comment by l-qiang** [comment]
@advancedfz 抱歉，是我没考虑周全。我以为大家都会通过IDE（例如：eclipse、IDEA）下载然后启动项目。
就你目前的情况来看。
1. 你需要下载一个maven，然后配置好环境变量。
2. 在你下载的项目的根目录下执行`mvn clean install -Dmaven.test.skip=true`。之后会在你的项目目录下生成\target\litter-baby-0.0.1-SNAPSHOT.jar
3. 在target目录下执行`java -jar litter-baby-0.0.1-SNAPSHOT.jar --user.phoneNum=学习强国用户名 --user.password=学习强国用户名`
这样就启动了。

**Comment by l-qiang** [comment]
我已经收到了。                                                                             刘强
